id: I7322A2E7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:52:06+00:00'
last_modified: '2022-06-07T20:45:41.113204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD53263
  title: ནང་པ་སངས་རྒྱས་དང་ཚན་རིག་སྨྲ་བ་གཉིས་ཀྱིས་འཇིག་རྟེན་ཆགས་ཚུལ་གྱི་རྣམ་བཞག་བཤད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    E5E3:
      image_group_id: I1PD53298
      title: ''
      total_pages: 226
      order: 1
      base_file: E5E3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
